add static-route next-hop and also add acctzsteam, instead of acctz (#4456)
* add static-route next-hop and also add acctzsteam, instead of acctz

* Added deviations, scale changes and gnmi.set was modified to gnmi.subscribe

* fixed the failure feature/gnsi/acctz/tests/record_payload_truncation/record_payload_truncation_test.go:69:18: undefined: recordRequestResult

* fixing comments

* reverting back to scale change